SET (CMAKE_ASM_COMPILER "powerpc64-unknown-linux-gnu-gcc")
SET (CMAKE_ASM-ATT_COMPILER "powerpc64-unknown-linux-gnu-gcc")
SET (CMAKE_C_COMPILER "powerpc64-unknown-linux-gnu-gcc")
SET (CMAKE_CXX_COMPILER "powerpc64-unknown-linux-gnu-g++")
SET (CMAKE_Fortran_COMPILER "powerpc64-unknown-linux-gnu-gfortran")
SET (CMAKE_AR /usr/bin/powerpc64-unknown-linux-gnu-ar CACHE FILEPATH "Archive manager" FORCE)
SET (CMAKE_RANLIB /usr/bin/powerpc64-unknown-linux-gnu-ranlib CACHE FILEPATH "Archive index generator" FORCE)
SET (CMAKE_SYSTEM_PROCESSOR "powerpc64")
SET (CMAKE_SYSTEM_NAME "Linux")
SET (CMAKE_FIND_ROOT_PATH "/usr/powerpc64-unknown-linux-gnu")
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
